/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.gui.mitarbeiter;

import java.util.ArrayList;
import javase.pf.haupt.Projekt;
import javase.pf.handler.MitarbeiterHandler;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class MitarbeiterJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MitarbeiterJFrame
     */
    public MitarbeiterJFrame() {
        initComponents();
        setSize(1000, 600);
    }

    private int mitarbeiterId;

    public void setBenutzernameUndBenutzerIdLabel(String benutzername, int benutzerId) {
        jLabelBenutzername.setText("Welcome " + benutzername + " - ( ID: " + benutzerId + " )");
    }

    public void setBenutzerId(int projektleiterId) {
        this.mitarbeiterId = projektleiterId;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBenutzername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekteMitarbeiter = new javax.swing.JTable();
        jButtonAufgabenAnzeigenErstellen = new javax.swing.JButton();
        jButtonAnfrageenAnzeigenErstellen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelBenutzername.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabelBenutzername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTableProjekteMitarbeiter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Projekt-ID", "Projektname", "Projektleiter-ID", "Projektleiter Name"
            }
        ));
        jScrollPane1.setViewportView(jTableProjekteMitarbeiter);

        jButtonAufgabenAnzeigenErstellen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonAufgabenAnzeigenErstellen.setText("Aufgaben");
        jButtonAufgabenAnzeigenErstellen.setPreferredSize(new java.awt.Dimension(350, 55));
        jButtonAufgabenAnzeigenErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAufgabenAnzeigenErstellenActionPerformed(evt);
            }
        });

        jButtonAnfrageenAnzeigenErstellen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonAnfrageenAnzeigenErstellen.setText("Anfragen");
        jButtonAnfrageenAnzeigenErstellen.setPreferredSize(new java.awt.Dimension(350, 55));
        jButtonAnfrageenAnzeigenErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnfrageenAnzeigenErstellenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBenutzername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAufgabenAnzeigenErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnfrageenAnzeigenErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAnfrageenAnzeigenErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButtonAufgabenAnzeigenErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonAufgabenAnzeigenErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAufgabenAnzeigenErstellenActionPerformed
        JFrameAufgabenMitarbeiter a = new JFrameAufgabenMitarbeiter();
        a.setMitarbeiterId(mitarbeiterId);
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonAufgabenAnzeigenErstellenActionPerformed

    private void jButtonAnfrageenAnzeigenErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnfrageenAnzeigenErstellenActionPerformed
        JFrameAnfrageMitarbeiter anfragen = new JFrameAnfrageMitarbeiter();
        anfragen.setMitarbeiterId(mitarbeiterId);
        anfragen.setLocationRelativeTo(null);
        anfragen.setVisible(true);
        anfragen.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonAnfrageenAnzeigenErstellenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getProjekteMitarbeiter();
    }//GEN-LAST:event_formWindowOpened

    public void getProjekteMitarbeiter() {
        //int projektleiterId = 25;

        ArrayList<Projekt> projektList = MitarbeiterHandler.getProjektByMitarbeiterId(mitarbeiterId);
        DefaultTableModel tm = (DefaultTableModel) jTableProjekteMitarbeiter.getModel();

        tm.setRowCount(0);

        for (Projekt p : projektList) {
            Object[] rowData = {
                p.getProjektId(),
                p.getProjektName(),
                p.getProjektleiterId(),
                p.getProjektleiterName()
            };
            tm.addRow(rowData);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MitarbeiterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MitarbeiterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnfrageenAnzeigenErstellen;
    private javax.swing.JButton jButtonAufgabenAnzeigenErstellen;
    private javax.swing.JLabel jLabelBenutzername;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjekteMitarbeiter;
    // End of variables declaration//GEN-END:variables
}
