/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.gui.verwaltung;

import java.util.ArrayList;
import javase.pf.haupt.Projekt;
import javase.pf.handler.VerwaltungHandler;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VerwaltungJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VerwaltungJFrame
     */
    public VerwaltungJFrame() {
        this.setLocationRelativeTo(null);
        initComponents();
        setSize(1000, 600);
    }

    public void setBenutzernameUndBenutzerIdLabel
        (String benutzername, int benutzerId) {
        jLabelBenutzername.setText
        ("Welcome " + benutzername + " - ( ID: " + benutzerId + " )");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekte = new javax.swing.JTable();
        jButtonMitarbeiter = new javax.swing.JButton();
        jButtonAufgaben = new javax.swing.JButton();
        jButtonAnfragen = new javax.swing.JButton();
        jLabelBenutzername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableProjekte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Projekt-ID", "Projektname", "Projektleiter-ID", "Erstell-Datum", "Endzeit-Datum"
            }
        ));
        jScrollPane1.setViewportView(jTableProjekte);

        jButtonMitarbeiter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonMitarbeiter.setText("Mitarbeiter");
        jButtonMitarbeiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMitarbeiterActionPerformed(evt);
            }
        });

        jButtonAufgaben.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonAufgaben.setText("Aufgaben");
        jButtonAufgaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAufgabenActionPerformed(evt);
            }
        });

        jButtonAnfragen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonAnfragen.setText("Anfragen");
        jButtonAnfragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnfragenActionPerformed(evt);
            }
        });

        jLabelBenutzername.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabelBenutzername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButtonMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButtonAufgaben, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButtonAnfragen, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jLabelBenutzername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAnfragen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButtonAufgaben, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMitarbeiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMitarbeiterActionPerformed
        VJFrameMitarbeiterTabelle mt = new VJFrameMitarbeiterTabelle();
        mt.setLocationRelativeTo(null);
        mt.setVisible(true);
        mt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonMitarbeiterActionPerformed

    private void jButtonAufgabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAufgabenActionPerformed
        VJFrameAufgabenTabelle a = new VJFrameAufgabenTabelle();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAufgabenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getAllProjekte();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAnfragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnfragenActionPerformed
        VJFrameAnfragenTabelle an = new VJFrameAnfragenTabelle();
        an.setLocationRelativeTo(null);
        an.setVisible(true);
        an.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAnfragenActionPerformed

    public void getAllProjekte() {
        ArrayList<Projekt> projektList = VerwaltungHandler.getAllProjekte();
        DefaultTableModel tm = (DefaultTableModel) jTableProjekte.getModel();
        tm.setRowCount(0);
        for (Projekt p : projektList) {
            Object[] rowData = {
                p.getProjektId(),
                p.getProjektName(),
                p.getProjektleiterId(),
                p.getErstellungDatum(),
                p.getEndzeitraumDatum()
            };
            tm.addRow(rowData);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerwaltungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerwaltungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerwaltungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerwaltungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerwaltungJFrame().setVisible(true);
            }
        });
    }

    public JLabel getjLabelBenutzername() {
        return jLabelBenutzername;
    }

    public void setjLabelBenutzername(JLabel jLabelBenutzername) {
        this.jLabelBenutzername = jLabelBenutzername;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnfragen;
    private javax.swing.JButton jButtonAufgaben;
    private javax.swing.JButton jButtonMitarbeiter;
    private javax.swing.JLabel jLabelBenutzername;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjekte;
    // End of variables declaration//GEN-END:variables
}
