/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.gui.verwaltung;

import java.util.ArrayList;
import javase.pf.haupt.Benutzer;
import javase.pf.handler.VerwaltungHandler;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VJFrameMitarbeiterTabelle extends javax.swing.JFrame {

    /**
     * Creates new form VJFrameMitarbeiterTabelle
     */
    public VJFrameMitarbeiterTabelle() {
        initComponents();
        setSize(960, 550);
    }

    public void gettAllMitarbeiter() {
        ArrayList<Benutzer> mitarbeiterList = VerwaltungHandler.gettAllMitarbeiter();
        DefaultTableModel tm = (DefaultTableModel) jTableMitarbeiter.getModel();
        tm.setRowCount(0);

        for (Benutzer b : mitarbeiterList) {
            Object[] rowData = {
                b.getBenutzerId(),
                b.getBenutzerVollName(),
                b.getRolle(),
                b.getMail(),
                b.getTelNummer(),
                b.getBenutzerName(),
                b.getPasswort()
            };
            tm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMitarbeiter = new javax.swing.JTable();
        jTextFieldRolle = new javax.swing.JTextField();
        jTextFieldVollName = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldPasswort = new javax.swing.JTextField();
        jTextFieldTelNummer = new javax.swing.JTextField();
        jTextFieldBenutzerName = new javax.swing.JTextField();
        jLabelTelNummer = new javax.swing.JLabel();
        jLabelVollName = new javax.swing.JLabel();
        jLabelRolle = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelBenutzerName = new javax.swing.JLabel();
        jLabelPasswort = new javax.swing.JLabel();
        jButtonBenutzerHinzufuegen = new javax.swing.JButton();
        jButtonBenutzerLoeschen = new javax.swing.JButton();
        jButtonBearbeiten = new javax.swing.JButton();
        jTextFieldBenutzerId = new javax.swing.JTextField();
        jLabelBenutzerId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableMitarbeiter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Benutzer-ID", "Voll Name", "Rolle", "Mail", "Tel.Nummer", "Benuter-Name", "Passwort"
            }
        ));
        jTableMitarbeiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMitarbeiterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMitarbeiter);

        jLabelTelNummer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelNummer.setText("Tel.Nummer");

        jLabelVollName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVollName.setText("Voll Name");

        jLabelRolle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRolle.setText("Rolle");

        jLabelMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMail.setText("Mail");

        jLabelBenutzerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBenutzerName.setText("Benutzer-Name");

        jLabelPasswort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPasswort.setText("Passwort");

        jButtonBenutzerHinzufuegen.setText("Benutzer hinzufügen");
        jButtonBenutzerHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBenutzerHinzufuegenActionPerformed(evt);
            }
        });

        jButtonBenutzerLoeschen.setText("Benutzer löschen");
        jButtonBenutzerLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBenutzerLoeschenActionPerformed(evt);
            }
        });

        jButtonBearbeiten.setText("Benutzerdaten bearbeiten");
        jButtonBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBearbeitenActionPerformed(evt);
            }
        });

        jTextFieldBenutzerId.setEditable(false);

        jLabelBenutzerId.setText("Benutzer-ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBenutzerHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBearbeiten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBenutzerLoeschen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBenutzerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBenutzerId, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelVollName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldVollName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelRolle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldRolle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBenutzerName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBenutzerName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldRolle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldBenutzerName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldVollName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldBenutzerId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBenutzerName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRolle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVollName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelBenutzerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonBearbeiten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBenutzerHinzufuegen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBenutzerLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        gettAllMitarbeiter();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonBenutzerHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBenutzerHinzufuegenActionPerformed
        String vollName = jTextFieldVollName.getText();
        String rolle = jTextFieldRolle.getText();
        String mail = jTextFieldMail.getText();
        String phone = jTextFieldTelNummer.getText();
        String benutzerName = jTextFieldBenutzerName.getText();
        String passwort = jTextFieldPasswort.getText();

        Benutzer benutzer = new Benutzer(vollName, rolle, mail,
                phone, benutzerName, passwort);
        VerwaltungHandler.benutzerHinzufuegen(benutzer);

        gettAllMitarbeiter();
        textFieldLeer();
        JOptionPane.showMessageDialog(null, "Mitarbeiter erfolgreich hinzufügt");
    }//GEN-LAST:event_jButtonBenutzerHinzufuegenActionPerformed

    private void jButtonBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBearbeitenActionPerformed
        int benutzerId = Integer.parseInt(jTextFieldBenutzerId.getText());
        String vollName = jTextFieldVollName.getText();
        String rolle = jTextFieldRolle.getText();
        String mail = jTextFieldMail.getText();
        String phone = jTextFieldTelNummer.getText();
        String benutzerName = jTextFieldBenutzerName.getText();
        String passwort = jTextFieldPasswort.getText();

        Benutzer benutzer = new Benutzer(benutzerId, vollName, rolle, mail,
                phone, benutzerName, passwort);
        VerwaltungHandler.benutzerBearbeiten(benutzer);

        DefaultTableModel tm = (DefaultTableModel) jTableMitarbeiter.getModel();

        tm.setValueAt(vollName, jTableMitarbeiter.getSelectedRow(), 1);
        tm.setValueAt(rolle, jTableMitarbeiter.getSelectedRow(), 2);
        tm.setValueAt(mail, jTableMitarbeiter.getSelectedRow(), 3);
        tm.setValueAt(phone, jTableMitarbeiter.getSelectedRow(), 4);
        tm.setValueAt(benutzerName, jTableMitarbeiter.getSelectedRow(), 5);
        tm.setValueAt(passwort, jTableMitarbeiter.getSelectedRow(), 6);

        gettAllMitarbeiter();
        textFieldLeer();
        JOptionPane.showMessageDialog(null, "Daten sind erfolgreich bearbeitet");
    }//GEN-LAST:event_jButtonBearbeitenActionPerformed


    private void jTableMitarbeiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMitarbeiterMouseClicked
        DefaultTableModel tm = (DefaultTableModel) jTableMitarbeiter.getModel();

        int benutzerId = (int) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 0);
        String vollName = (String) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 1);
        String rolle = (String) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 2);
        String mail = (String) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 3);
        String phone = (String) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 4);
        String benutzername = (String) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 5);
        String passwort = (String) tm.getValueAt(jTableMitarbeiter.getSelectedRow(), 6);

        jTextFieldBenutzerId.setText(String.valueOf(benutzerId));
        jTextFieldVollName.setText(vollName);
        jTextFieldRolle.setText(rolle);
        jTextFieldMail.setText(mail);
        jTextFieldTelNummer.setText(phone);
        jTextFieldBenutzerName.setText(benutzername);
        jTextFieldPasswort.setText(passwort);

    }//GEN-LAST:event_jTableMitarbeiterMouseClicked

    private void jButtonBenutzerLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBenutzerLoeschenActionPerformed
        int benutzerId = Integer.parseInt(jTextFieldBenutzerId.getText());
        VerwaltungHandler.benutzerLoeschen(benutzerId);

        gettAllMitarbeiter();
        textFieldLeer();
        JOptionPane.showMessageDialog(null, "Daten sind gelöscht");
    }//GEN-LAST:event_jButtonBenutzerLoeschenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VJFrameMitarbeiterTabelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VJFrameMitarbeiterTabelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VJFrameMitarbeiterTabelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VJFrameMitarbeiterTabelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VJFrameMitarbeiterTabelle().setVisible(true);
            }
        });
    }

    public void textFieldLeer() {
        jTextFieldBenutzerId.setText(null);
        jTextFieldVollName.setText(null);
        jTextFieldRolle.setText(null);
        jTextFieldMail.setText(null);
        jTextFieldTelNummer.setText(null);
        jTextFieldBenutzerName.setText(null);
        jTextFieldPasswort.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBearbeiten;
    private javax.swing.JButton jButtonBenutzerHinzufuegen;
    private javax.swing.JButton jButtonBenutzerLoeschen;
    private javax.swing.JLabel jLabelBenutzerId;
    private javax.swing.JLabel jLabelBenutzerName;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelPasswort;
    private javax.swing.JLabel jLabelRolle;
    private javax.swing.JLabel jLabelTelNummer;
    private javax.swing.JLabel jLabelVollName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMitarbeiter;
    private javax.swing.JTextField jTextFieldBenutzerId;
    private javax.swing.JTextField jTextFieldBenutzerName;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldPasswort;
    private javax.swing.JTextField jTextFieldRolle;
    private javax.swing.JTextField jTextFieldTelNummer;
    private javax.swing.JTextField jTextFieldVollName;
    // End of variables declaration//GEN-END:variables
}
