/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.nichts;

import javase.pf.nichts.HauptJFrame;

/**
 *
 * @author user
 */
public class NewJFrameMaster extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameMaster
     */
    public NewJFrameMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jVerwaltung = new javax.swing.JButton();
        jProjektleiter = new javax.swing.JButton();
        jMitarbeiter = new javax.swing.JButton();
        jTitel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jVerwaltung.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jVerwaltung.setText("Verwaltung");
        jVerwaltung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerwaltungActionPerformed(evt);
            }
        });

        jProjektleiter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jProjektleiter.setText("Projektleiter");

        jMitarbeiter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jMitarbeiter.setText("Mitarbeiter");
        jMitarbeiter.setPreferredSize(null);

        jTitel.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jTitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitel.setText("ProjektFlow");
        jTitel.setPreferredSize(null);

        jDesktopPane1.setLayer(jVerwaltung, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jProjektleiter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jMitarbeiter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTitel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jVerwaltung, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jProjektleiter, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
            .addComponent(jTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVerwaltung, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(jProjektleiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVerwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerwaltungActionPerformed
        // hier wollte ich JInternalFrameVerwaltung verwendet "Internal"
        //JInternalFrameVerwaltung verwaltungScreen = new JInternalFrameVerwaltung();
        //verwaltungScreen.setVisible(true);
        //jPanelDesktop.add(verwaltungScreen);

        /*
        JFrameVerwaltung jVerwaltung = new JFrameVerwaltung();
        jVerwaltung.setVisible(true);

        VerwaltungJFrame jV = new VerwaltungJFrame();
        jV.setVisible(true);
        */

        HauptJFrame n = new HauptJFrame();
        n.setVisible(true);
        jDesktopPane1.add(n);

    }//GEN-LAST:event_jVerwaltungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jMitarbeiter;
    private javax.swing.JButton jProjektleiter;
    private javax.swing.JLabel jTitel;
    private javax.swing.JButton jVerwaltung;
    // End of variables declaration//GEN-END:variables
}
