/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.nichts;

import javase.pf.gui.verwaltung.JFrameLoginVerwalter;
import javax.swing.JLabel;



/**
 *
 * @author user
 */
public class Verwaltung__JFrame extends javax.swing.JFrame {

    /**
     * Creates new form VerwaltungJFrame
     */
    public Verwaltung__JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Mein Code----
        //setSize(1000, 800);
    }

    public void setBenutzernameLabel(String benutzername){
        jLabelBenutzername.setText("Welcome "+ benutzername);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekte = new javax.swing.JTable();
        jMitarbeiter = new javax.swing.JButton();
        AufgabenButton = new javax.swing.JButton();
        jVerwaltung = new javax.swing.JButton();
        jLabelBenutzername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableProjekte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Projekt-ID", "Projektname", "Projektleiter-ID", "Erstell-Datum", "Endzeit-Datum"
            }
        ));
        jScrollPane1.setViewportView(jTableProjekte);

        jMitarbeiter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jMitarbeiter.setText("Mitarbeiter");

        AufgabenButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AufgabenButton.setText("Aufgaben");
        AufgabenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AufgabenButtonActionPerformed(evt);
            }
        });

        jVerwaltung.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jVerwaltung.setText("Verwaltung");
        jVerwaltung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerwaltungActionPerformed(evt);
            }
        });

        jLabelBenutzername.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabelBenutzername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jVerwaltung, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(AufgabenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jLabelBenutzername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMitarbeiter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(AufgabenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jVerwaltung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JFrameLoginVerwalter log = new JFrameLoginVerwalter();
        String eingegebenerBenutzername = jLabelBenutzername.getText();
        log.setBenuterName(eingegebenerBenutzername);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void AufgabenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AufgabenButtonActionPerformed
        
    }//GEN-LAST:event_AufgabenButtonActionPerformed

    private void jVerwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerwaltungActionPerformed

        /*VerwaltungJFrame jV = new VerwaltungJFrame();
        jV.setVisible(true);*/
    }//GEN-LAST:event_jVerwaltungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verwaltung__JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verwaltung__JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verwaltung__JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verwaltung__JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verwaltung__JFrame().setVisible(true);
            }
        });
    }

    public JLabel getjLabelBenutzername() {
        return jLabelBenutzername;
    }

    public void setjLabelBenutzername(JLabel jLabelBenutzername) {
        this.jLabelBenutzername = jLabelBenutzername;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AufgabenButton;
    private javax.swing.JLabel jLabelBenutzername;
    private javax.swing.JButton jMitarbeiter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjekte;
    private javax.swing.JButton jVerwaltung;
    // End of variables declaration//GEN-END:variables
}
