/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.gui.haupt;

import javase.pf.gui.projektleiter.JFrameLoginProjektleiter;
import javase.pf.gui.mitarbeiter.JFrameLoginMitarbeiter;
import javase.pf.gui.verwaltung.JFrameLoginVerwalter;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class JFrameHauptPF extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFrameHauptPF() {
        initComponents();
        setSize(1000, 700);
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVerwaltung = new javax.swing.JButton();
        jButtonProjektleiter = new javax.swing.JButton();
        jButtonMitarbeiter = new javax.swing.JButton();
        jTitel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVerwaltung.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonVerwaltung.setText("Verwaltung");
        jButtonVerwaltung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerwaltungActionPerformed(evt);
            }
        });

        jButtonProjektleiter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonProjektleiter.setText("Projektleiter");
        jButtonProjektleiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjektleiterActionPerformed(evt);
            }
        });

        jButtonMitarbeiter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonMitarbeiter.setText("Mitarbeiter");
        jButtonMitarbeiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMitarbeiterActionPerformed(evt);
            }
        });

        jTitel.setFont(new java.awt.Font("Segoe Print", 1, 75)); // NOI18N
        jTitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitel.setText("ProjektFlow");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButtonVerwaltung, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButtonProjektleiter, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButtonMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
            .addComponent(jTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTitel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonVerwaltung, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addComponent(jButtonProjektleiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMitarbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMitarbeiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMitarbeiterActionPerformed
        JFrameLoginMitarbeiter login = new JFrameLoginMitarbeiter();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonMitarbeiterActionPerformed

    private void jButtonVerwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerwaltungActionPerformed
        JFrameLoginVerwalter login = new JFrameLoginVerwalter();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonVerwaltungActionPerformed

    private void jButtonProjektleiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjektleiterActionPerformed
        JFrameLoginProjektleiter login = new JFrameLoginProjektleiter();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonProjektleiterActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHauptPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHauptPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHauptPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHauptPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHauptPF().setVisible(true);
            }
        });
    }

    
    public JButton getjMitarbeiter() {
        return jButtonMitarbeiter;
    }

    public void setjMitarbeiter(JButton jMitarbeiter) {
        this.jButtonMitarbeiter = jMitarbeiter;
    }

    public JButton getjProjektleiter() {
        return jButtonProjektleiter;
    }

    public void setjProjektleiter(JButton jProjektleiter) {
        this.jButtonProjektleiter = jProjektleiter;
    }

    public JLabel getjTitel() {
        return jTitel;
    }

    public void setjTitel(JLabel jTitel) {
        this.jTitel = jTitel;
    }

    public JButton getjVerwaltung() {
        return jButtonVerwaltung;
    }

    public void setjVerwaltung(JButton jVerwaltung) {
        this.jButtonVerwaltung = jVerwaltung;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMitarbeiter;
    private javax.swing.JButton jButtonProjektleiter;
    private javax.swing.JButton jButtonVerwaltung;
    private javax.swing.JLabel jTitel;
    // End of variables declaration//GEN-END:variables
}
