/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.gui.projektleiter;

import java.util.ArrayList;
import javase.pf.haupt.Aufgaben;
import javase.pf.handler.ProjektleiterHandler;
import javase.pf.handler.VerwaltungHandler;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class JFrameAufgabenErstellenAnzeigenProjektleiter extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAufgabeErstellen
     */
    public JFrameAufgabenErstellenAnzeigenProjektleiter() {
        initComponents();
        setSize(960, 550);
    }

    private int projektleiterId;

    public void setProjektleiterId(int projektleiterId) {
        this.projektleiterId = projektleiterId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAufgabenVonProjektleiter = new javax.swing.JTable();
        jLabelZeitraumTage = new javax.swing.JLabel();
        jTextFieldZeitraumTage = new javax.swing.JTextField();
        jTextFieldProjektId = new javax.swing.JTextField();
        jLabelProjektId = new javax.swing.JLabel();
        jLabelMitarbeiterId = new javax.swing.JLabel();
        jTextFieldMitarbeiterId = new javax.swing.JTextField();
        jLabelAufgabeBeschreibung = new javax.swing.JLabel();
        jButtonErstellen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBeschreibung = new javax.swing.JTextArea();
        jButtonAufgabeBeschreibungAnzeigen = new javax.swing.JButton();
        jTextFieldAufgabeId = new javax.swing.JTextField();
        jLabelAufgabeAnzeigen = new javax.swing.JLabel();
        jLabelLinie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableAufgabenVonProjektleiter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aufgabe-ID", "Projekt-ID", "M-ID", "M-Name", "Zeitraum", "Status", "Erstell-Datum", "Beschreibung"
            }
        ));
        jScrollPane1.setViewportView(jTableAufgabenVonProjektleiter);

        jLabelZeitraumTage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZeitraumTage.setText("Zeitraum Tage");

        jLabelProjektId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProjektId.setText("Projekt ID");

        jLabelMitarbeiterId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMitarbeiterId.setText("Mitarbeiter ID");

        jLabelAufgabeBeschreibung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAufgabeBeschreibung.setText(" Die Aufgabe");

        jButtonErstellen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonErstellen.setText("Erstellen");
        jButtonErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErstellenActionPerformed(evt);
            }
        });

        jTextAreaBeschreibung.setColumns(20);
        jTextAreaBeschreibung.setRows(5);
        jScrollPane2.setViewportView(jTextAreaBeschreibung);

        jButtonAufgabeBeschreibungAnzeigen.setText("Aufgabe anzeigen");
        jButtonAufgabeBeschreibungAnzeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAufgabeBeschreibungAnzeigenActionPerformed(evt);
            }
        });

        jLabelAufgabeAnzeigen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAufgabeAnzeigen.setText("Geben Sie die Aufgabe-ID an, um die Beschreibung anzusehen .");

        jLabelLinie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelZeitraumTage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldZeitraumTage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProjektId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProjektId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMitarbeiterId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMitarbeiterId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jButtonErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jLabelAufgabeBeschreibung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAufgabeAnzeigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAufgabeId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAufgabeBeschreibungAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLinie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldAufgabeId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAufgabeAnzeigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonAufgabeBeschreibungAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLinie, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAufgabeBeschreibung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMitarbeiterId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMitarbeiterId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProjektId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProjektId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelZeitraumTage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldZeitraumTage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getAllAufgaben();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErstellenActionPerformed
        int mitarbeiterId = Integer.parseInt(jTextFieldMitarbeiterId.getText());
        int projektId = Integer.parseInt(jTextFieldProjektId.getText());
        int zeitraum = Integer.parseInt(jTextFieldZeitraumTage.getText());
        String beschreibung = jTextAreaBeschreibung.getText();

        Aufgaben aufgabe = new Aufgaben(projektleiterId, mitarbeiterId, projektId, zeitraum, beschreibung);
        ProjektleiterHandler.neueAufgabeErstellen(aufgabe);

        getAllAufgaben();
        textFieldLeer();
        JOptionPane.showMessageDialog(null, "Neue Aufgabe wurde erfolgreich erstellt");

    }//GEN-LAST:event_jButtonErstellenActionPerformed

    private void jButtonAufgabeBeschreibungAnzeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAufgabeBeschreibungAnzeigenActionPerformed
        /**/
        int aufgabeId = Integer.parseInt(jTextFieldAufgabeId.getText());

        String nachricht = VerwaltungHandler.aufgabeBeschreibungBayAufgabeId(aufgabeId);

        JFrame nachrichtFenster = new JFrame("Die Aufgabe");
        nachrichtFenster.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JLabel beschreibungLabel = new JLabel("<html><body>" + "Anfragebeschreibung: " + nachricht + "</body></html>");
        beschreibungLabel.setHorizontalAlignment(SwingConstants.CENTER);

        nachrichtFenster.add(beschreibungLabel);

        int width = 400;
        int height = 200;
        nachrichtFenster.setSize(width, height);

        textFieldLeer();
        nachrichtFenster.setLocationRelativeTo(null);
        nachrichtFenster.setVisible(true);
    }//GEN-LAST:event_jButtonAufgabeBeschreibungAnzeigenActionPerformed

    public void getAllAufgaben() {
        ArrayList<Aufgaben> aufgabenList = ProjektleiterHandler.getAufgabenByProjektleiterID(projektleiterId);
        DefaultTableModel tm = (DefaultTableModel) jTableAufgabenVonProjektleiter.getModel();
        tm.setRowCount(0);

        for (Aufgaben a : aufgabenList) {
            Object[] rowData = {
                a.getAufgabeId(),
                a.getProjektId(),
                a.getMitarbeiterId(),
                a.getMitarbeiterName(),
                a.getZeitraumTage(),
                a.getStatus(),
                a.getErstellungDatum(),
                a.getBeschreibung()
            };
            tm.addRow(rowData);
        }
    }

    public void textFieldLeer() {
        //jTextFieldProjektleiterId.setText(null);
        jTextFieldMitarbeiterId.setText(null);
        jTextFieldProjektId.setText(null);
        jTextFieldZeitraumTage.setText(null);
        jTextAreaBeschreibung.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAufgabenErstellenAnzeigenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAufgabenErstellenAnzeigenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAufgabenErstellenAnzeigenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAufgabenErstellenAnzeigenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAufgabenErstellenAnzeigenProjektleiter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAufgabeBeschreibungAnzeigen;
    private javax.swing.JButton jButtonErstellen;
    private javax.swing.JLabel jLabelAufgabeAnzeigen;
    private javax.swing.JLabel jLabelAufgabeBeschreibung;
    private javax.swing.JLabel jLabelLinie;
    private javax.swing.JLabel jLabelMitarbeiterId;
    private javax.swing.JLabel jLabelProjektId;
    private javax.swing.JLabel jLabelZeitraumTage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAufgabenVonProjektleiter;
    private javax.swing.JTextArea jTextAreaBeschreibung;
    private javax.swing.JTextField jTextFieldAufgabeId;
    private javax.swing.JTextField jTextFieldMitarbeiterId;
    private javax.swing.JTextField jTextFieldProjektId;
    private javax.swing.JTextField jTextFieldZeitraumTage;
    // End of variables declaration//GEN-END:variables
}
