/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javase.pf.gui.projektleiter;

import java.util.ArrayList;
import javase.pf.haupt.Anfrage;
import javase.pf.handler.ProjektleiterHandler;
import javase.pf.handler.VerwaltungHandler;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class JFrameAnfragenProjektleiter extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAnfragen
     */
    public JFrameAnfragenProjektleiter() {
        initComponents();
        setSize(960, 550);
    }

    private int projektleiterId;

    public void setProjektleiterId(int projektleiterId) {
        this.projektleiterId = projektleiterId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBeschreibung = new javax.swing.JTextArea();
        jButtonErstellen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnfragen = new javax.swing.JTable();
        jLabelAnfrageBeschreibung = new javax.swing.JLabel();
        jButtonAnfrageAnzeigen = new javax.swing.JButton();
        jTextFieldAnfrageId = new javax.swing.JTextField();
        jLabelLinie = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextAreaBeschreibung.setColumns(20);
        jTextAreaBeschreibung.setRows(5);
        jScrollPane2.setViewportView(jTextAreaBeschreibung);

        jButtonErstellen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonErstellen.setText("Erstellen");
        jButtonErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErstellenActionPerformed(evt);
            }
        });

        jTableAnfragen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Anfrage-ID", "Nachricht", "Erstell-Datum"
            }
        ));
        jScrollPane1.setViewportView(jTableAnfragen);

        jLabelAnfrageBeschreibung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnfrageBeschreibung.setText("Neue Anfrage");

        jButtonAnfrageAnzeigen.setText("Anfrage anzeigen");
        jButtonAnfrageAnzeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnfrageAnzeigenActionPerformed(evt);
            }
        });

        jLabelLinie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Geben Sie die Anfrage-ID an, für die Sie die Nachricht sehen möchten.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLinie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonErstellen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnfrageId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnfrageAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelAnfrageBeschreibung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAnfrageId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAnfrageAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLinie, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAnfrageBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jButtonErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErstellenActionPerformed
        String beschreibung = jTextAreaBeschreibung.getText();

        Anfrage anfrage = new Anfrage(projektleiterId, beschreibung);
        ProjektleiterHandler.anfrageAnVerwaltungErstellen(anfrage);

        gettMeinAnfragenAnVerwaltung();
        textFieldLeer();
        JOptionPane.showMessageDialog(null, "Neue Anfrage wurde erfolgreich erstellt");

    }//GEN-LAST:event_jButtonErstellenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        gettMeinAnfragenAnVerwaltung();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAnfrageAnzeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnfrageAnzeigenActionPerformed

        int aufgabeId = Integer.parseInt(jTextFieldAnfrageId.getText());

        String nachricht = VerwaltungHandler.anfrageNachrichtByProjektleiterId(aufgabeId);

        JFrame nachrichtFenster = new JFrame("Die Anfrage");
        nachrichtFenster.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JLabel beschreibungLabel = new JLabel("<html><body>" + "Anfragebeschreibung: " + nachricht + "</body></html>");
        beschreibungLabel.setHorizontalAlignment(SwingConstants.CENTER);

        nachrichtFenster.add(beschreibungLabel);

        int width = 400;
        int height = 200;
        nachrichtFenster.setSize(width, height);

        textFieldLeer();
        nachrichtFenster.setLocationRelativeTo(null);
        nachrichtFenster.setVisible(true);
    }//GEN-LAST:event_jButtonAnfrageAnzeigenActionPerformed

    public void gettMeinAnfragenAnVerwaltung() {
        ArrayList<Anfrage> anfragenList = ProjektleiterHandler.getErstellteAnfragenAnVerwaltung(projektleiterId);
        DefaultTableModel tm = (DefaultTableModel) jTableAnfragen.getModel();
        tm.setRowCount(0);

        for (Anfrage a : anfragenList) {
            Object[] rowData = {
                a.getAnfrageId(),
                a.getNachricht(),
                a.getErstellDatum()
            };
            tm.addRow(rowData);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAnfragenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAnfragenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAnfragenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAnfragenProjektleiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAnfragenProjektleiter().setVisible(true);
            }
        });
    }

    public void textFieldLeer() {
        jTextAreaBeschreibung.setText(null);
        jTextFieldAnfrageId.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnfrageAnzeigen;
    private javax.swing.JButton jButtonErstellen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAnfrageBeschreibung;
    private javax.swing.JLabel jLabelLinie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAnfragen;
    private javax.swing.JTextArea jTextAreaBeschreibung;
    private javax.swing.JTextField jTextFieldAnfrageId;
    // End of variables declaration//GEN-END:variables
}
